### ISSUE TITLE
Unhandled exception occurred at $004100F7: EAccess Violation: Access Violation

### ISSUE THREAD

**Issue by chiquitto** [neodynamic/WebClientPrintPHP3-Sample#1]
During printing, this error message is displayed.

![captura de tela 2017-02-06 as 11 21 46](https://cloud.githubusercontent.com/assets/2262702/22648741/21b6d0dc-ec5f-11e6-928e-51d648f575ab.png)

My PHP script is generating these commands

[saida.txt](https://github.com/neodynamic/WebClientPrintPHP3-Sample/files/754713/saida.txt)

**Comment by neodynamic** [comment]
Please send a ticket through https://neodynamic.com/support
