### ISSUE TITLE
Facing an Issue of incorrect url, Version 2

### ISSUE THREAD

**Issue by princy152** [neodynamic/WebClientPrintPHP3-Sample#2]
<img width="666" alt="screen shot 2017-09-06 at 4 49 46 am" src="https://user-images.githubusercontent.com/2134696/30087563-0cddff80-92bf-11e7-833d-55c1b82ac4d6.png">

**Comment by neodynamic** [comment]
Do you mean that error happens in v2.0? Please send a ticket through https://neodynamic.com/support with further details about the issue
